name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: devkitARM Bootstrap
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -S --noconfirm nds-dev

      - name: Build mini
        run: |
          source /etc/profile.d/devkit-env.sh
          pwd
          make

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: armboot.bin
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: armboot.bin
          tag: ${{ github.ref }}
          file_glob: true
